name: jksb

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Cherkout
      uses: actions/checkout@v2

    - name: Install firefox and packages
      run: |
        sudo apt-get update -y
        sudo apt-get -y install firefox
        pip install -r requirements.txt
    - name: Run Spider in VPN
      uses: zhangt2333/actions-easyconnect@main
      env:
        NETID: ${{secrets.NETID}}
        PASSWORD: ${{secrets.PASSWORD}}
        RECURL: ${{secrets.RECURL}}
        SEND_KEY: ${{secrets.SEND_KEY}}
        PYTHONIOENCODING: utf-8
        PYTHONLEGACYWINDOWSSTDIO: utf-8
      with:
          CLI_OPTS: ${{ secrets.CLI_OPTS }}
          RETRY: 2
          SLEEP_AFTER_LOGIN: 1
          EXPECTED_EXIT_CODE: 66
          # 先通链路再运行脚本
          SCRIPT: |
            python jksb_sysu.py
